// Do not modify the namespace, class name, or Auto generated fields.
// Modify the Excel Loader instead.
namespace SAB.Item
{
    public class ItemBaseDto
    {
        // <auto-generated>
        public int ID;
        public string NameKey;
        public ItemCategory Category;
        // </auto-generated>
    }
}
