// Do not modify the namespace, class name, or Auto generated fields.
// Modify the Excel Loader instead.
namespace SAB.Item
{
    public class ItemEquipmentDto
    {
        // <auto-generated>
        public int ID;
        public EquipSlot Slot;
        public string MeshPath;
        // </auto-generated>
    }
}
