// Do not modify the namespace, class name, or Auto generated fields.
// Modify the Excel Loader instead.
namespace SAB.Item
{
    public class ItemWeaponDto
    {
        // <auto-generated>
        public int ID;
        public float Damage;
        public int UpgradeSlot;
        public WeaponType WeaponType;
        public  WeaponHandedness Handedness;
        // </auto-generated>
    }
}
