using System;
using System.Collections.Generic;
using System.Text;

namespace Chu.Tools
{
    public static class DTOScriptCreater
    {
        public const string AutoGeneratedMarkerStart = "// <auto-generated>";
        public const string AutoGeneratedMarkerEnd = "// </auto-generated>";
        public const string Tap = "    ";

        public static string CreateScript(DataTableConfig config, SheetData data)
        {
            if (string.IsNullOrWhiteSpace(data.NameSpace))
                throw new Exception($"Namespace is empty.\nSheet Name : {data.GetPascalCaseName()}");

            var sb = new StringBuilder();

            foreach (var item in data.FieldNameByType)
            {
                if (config.NameSpaceByType.TryGetValue(item.Item1, out var text) == false)
                    continue;

                sb.Append($"using {text};\n");
            }
            if (sb.Length != 0)
                sb.Append("\n");

            sb.Append("// Do not modify the namespace, class name, or Auto generated fields.\n");
            sb.Append("// Modify the Excel Loader instead.\n");
            sb.Append($"namespace {data.NameSpace}\n");
            sb.Append("{\n");

            sb.Append($"{Tap}public class {config.GetScriptFileName(data.GetPascalCaseName())}\n");
            sb.Append($"{Tap}{{\n");

            sb.Append($"{Tap}{Tap}{AutoGeneratedMarkerStart}\n");
            WriteAutoGeneratedField(sb, data.FieldNameByType);
            sb.Append($"{Tap}{Tap}{AutoGeneratedMarkerEnd}\n");

            sb.Append($"{Tap}}}\n");
            sb.Append("}\n");

            return sb.ToString();
        }

        public static string ChangeGeneratedCode(string scriptText, List<(string, string)> nameByType)
        {
            scriptText = scriptText.Replace("\r\n", "\n");

            int header = scriptText.IndexOf(AutoGeneratedMarkerStart, StringComparison.Ordinal);
            if (header < 0)
                throw new Exception($"Auto Generated Start Marker not found.\nscriptText : {scriptText}");
            header = scriptText.LastIndexOf("\n", header) + 1;

            int tail = scriptText.IndexOf(AutoGeneratedMarkerEnd, header, StringComparison.Ordinal);
            if (tail < 0)
                throw new Exception($"Auto Generated End Marker not found.\nscriptText : {scriptText}");
            tail = scriptText.IndexOf("\n", tail, StringComparison.Ordinal);
            if (tail < 0)
                tail = scriptText.Length;

            var sb = new StringBuilder();
            sb.Append($"{Tap}{Tap}{AutoGeneratedMarkerStart}\n");
            WriteAutoGeneratedField(sb, nameByType);
            sb.Append($"{Tap}{Tap}{AutoGeneratedMarkerEnd}\n");

            scriptText = scriptText.Remove(header, tail - header + 1);
            scriptText = scriptText.Insert(header, sb.ToString());

            return scriptText;
        }

        private static void WriteAutoGeneratedField(StringBuilder sb, List<(string, string)> nameByType)
        {
            for (int i = 0; i < nameByType.Count; i++)
            {
                sb.Append($"{Tap}{Tap}public {nameByType[i].Item2} {nameByType[i].Item1};\n");
            }
        }
    }
}
