// Do not modify the namespace, class name, or Auto generated fields.
// Modify the Excel Loader instead.
namespace SAB.Skill
{
    public class SkillSequenceDto
    {
        // <auto-generated>
        public int ID;
        public int LogicID;
        public int Order;
        // </auto-generated>
    }
}
