// Do not modify the namespace, class name, or Auto generated fields.
// Modify the Excel Loader instead.
namespace SAB.Skill
{
    public class SkillStepDoTDto
    {
        // <auto-generated>
        public int ID;
        public float DamageRate;
        public float Duration;
        // </auto-generated>
    }
}
