using Chu.Collision;

// Do not modify the namespace, class name, or Auto generated fields.
// Modify the Excel Loader instead.
namespace SAB.Skill
{
    public class SkillHitBoxDto
    {
        // <auto-generated>
        public int ID;
        public ShapeType ShapeType;
        public float Rotation;
        public float Param1;
        public float Param2;
        public float OffsetX;
        public float OffsetY;
        // </auto-generated>
    }
}
