// Do not modify the namespace, class name, or Auto generated fields.
// Modify the Excel Loader instead.
namespace SAB.Skill
{
    public class SkillSetDto
    {
        // <auto-generated>
        public int SetID;
        public int SkillID;
        // </auto-generated>
    }
}
