// Do not modify the namespace, class name, or Auto generated fields.
// Modify the Excel Loader instead.
namespace SAB.Skill
{
    public class SkillStepAoEDto
    {
        // <auto-generated>
        public int ID;
        public float DamageRate;
        public float Ranged;
        public int Count;
        // </auto-generated>
    }
}
