// Do not modify the namespace, class name, or Auto generated fields.
// Modify the Excel Loader instead.
namespace SAB.Skill
{
    public class SkillBaseDto
    {
        // <auto-generated>
        public int ID;
        public string NameKey;
        public float CastingTime;
        public float Cooldown;
        public float Cost;
        public string MotionFileName;
        public int ObjectLogicID;
        public int MaxHitCount;
        // </auto-generated>
    }
}
