// Do not modify the namespace, class name, or Auto generated fields.
// Modify the Excel Loader instead.
namespace SAB.Skill
{
    public class SkillCollisionLogicDto
    {
        // <auto-generated>
        public int ID;
        public int Order;
        public int HitboxID;
        public float ActiveTime;
        public float Speed;
        public int SequenceID;
        // </auto-generated>
    }
}
