// Do not modify the namespace, class name, or Auto generated fields.
// Modify the Excel Loader instead.
namespace SAB.Unit
{
    public class CharacterBaseStatsDto
    {
        // <auto-generated>
        public int ID;
        public string NameKey;
        public string DescKey;
        public FactionType Faction;
        public float HP;
        public float ATK;
        public float PDEF;
        public float MDEF;
        public float SPD;
        public int SkillSetID;
        // </auto-generated>
    }
}
