// Do not modify the namespace, class name, or Auto generated fields.
// Modify the Excel Loader instead.
namespace SAB.Unit
{
    public class HumanDefaultEquipmentDto
    {
        // <auto-generated>
        public int ID;
        public int EquipmentID;
        // </auto-generated>
    }
}
