// Do not modify the namespace, class name, or Auto generated fields.
// Modify the Excel Loader instead.
namespace SAB.Unit
{
    public class HumanCustomizingDto
    {
        // <auto-generated>
        public int ID;
        public Gender Gender;
        public int Eye;
        public int Mouth;
        public int Hair;
        public int Eyebrow;
        // </auto-generated>
    }
}
